Update gradle_ci.yml

diff --git a/.github/workflows/gradle_ci.yml b/.github/workflows/gradle_ci.yml
--- a/.github/workflows/gradle_ci.yml
+++ b/.github/workflows/gradle_ci.yml
@@ -19,43 +19,61 @@ jobs:
           java-version: '17'
           distribution: 'temurin'
           cache: 'gradle'
-      - id: gradle_build
-        name: Build with Gradle
+      - name: Check project version
         run: |
           chmod +x gradlew
-          ./gradlew -PremoteMavenRepositoryUrl=$(pwd)/build/temp-maven-repo publish
-          echo "project_version=$(./gradlew properties | grep 'version:\s')" >> "$GITHUB_OUTPUT"
-      - name: Upload temporary maven repository
-        uses: actions/upload-artifact@v3
-        with:
-          name: temp-maven-repo
-          path: build/temp-maven-repo
-    outputs:
-      project_version: ${{ steps.gradle_build.outputs.project_version }}
-  publish:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: Check project version
-        env:
-          project_version: ${{ needs.build.outputs.project_version }}
-        run: |
+          project_version=$(./gradlew properties | grep 'version:\s')
           echo "\$project_version: \"$project_version\""
+          if [ "$project_version" = '' ]; then
+            echo 'Cannot read version information of root project!'
+            exit 10
+          fi
           if [ "$(echo $project_version | grep -i dev)" != '' ]; then
             echo 'Cannot publish development versions!'
             exit 10
           fi
-      - name: Download temporary maven repository
-        uses: actions/download-artifact@v3
-        with:
-          name: temp-maven-repo
-          path: build/temp-maven-repo
       - name: Clone remote maven repository
         run: |
           git clone ${{ secrets.REMOTE_MAVEN_REPO_URL }}
+      - id: gradle_build
+        name: Build with Gradle
+        run: |
+          ./gradlew -PremoteMavenRepositoryUrl=$(pwd)/maven-repo/repository publish
+          tar -zcf maven-repo.tar.gz maven-repo/repository
+          mkdir remote-maven-repo-copy
+          mv maven-repo.tar.gz remote-maven-repo-copy/
+      - name: Upload remote maven repository as artifact
+        uses: actions/upload-artifact@v3
+        with:
+          # 指定要上传的目录在上传到当前Actions运行实例的Artifacts当中时要使用的名字
+          name: remote-maven-repo-copy
+          # 要上传的目录路径（以项目根目录为相对路径起始点）
+          path: remote-maven-repo-copy
+  publish:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Download temporary maven repository
+        uses: actions/download-artifact@v3
+        with:
+          # 指定在之前的job当中，上传到Actions运行实例的Artifacts当中的目录所使用的名字
+          name: remote-maven-repo-copy
+          # 指定要将这一目录下的所有内容（即不包含目录本身）下载到哪个位置（以项目根目录为相对路径起始点）
+          path: remote-maven-repo-copy
+      - name: Clone remote maven repository
+        run: |
+          # 将kosaka-bun/maven-repo的git仓库clone到项目根目录下
+          git clone ${{ secrets.REMOTE_MAVEN_REPO_URL }}
       - name: Merge maven repository and publish
         run: |
-          cp -rf build/temp-maven-repo/* maven-repo/repository/
+          # 解压maven-repo.tar.gz
+          cd remote-maven-repo-copy
+          tar -zxf maven-repo.tar.gz
+          cd ..
+          # 将[项目根目录]/remote-maven-repo-copy/maven-repo/repository下所有内容，复制到[项目根目录]/maven-repo/repository下
+          # 并替换已存在的内容
+          cp -rf remote-maven-repo-copy/maven-repo/repository/* maven-repo/repository/
+          # 进入名为maven-repo的git仓库，设置提交者信息，然后提交并推送
           cd maven-repo/repository
           git config --global user.name 'Kosaka Bun'
           git config --global user.email 'kosaka-bun@qq.com'
